---
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hsmw-mobil-heimdall
    environment: 
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - "data:/home/bot/workdir/data:rw"
      - "commands:/home/bot/workdir/app/commands:rw"

volumes:
  data:
  commands: